/**
 * Seed catalog of providers and models. Scores are starting assumptions
 * (0..1) until benchmarks measure them; costs are USD estimates used only for
 * pre-submission budget checks (actual cost comes from the provider response).
 * Model ids verified against provider docs on the date in docs/RESEARCH.md §8.
 * Bump CATALOG_VERSION whenever an entry changes.
 */
export const CATALOG_VERSION = 2;

export interface CatalogModel {
  provider: string;
  model: string;
  displayName: string;
  capabilities: string[];
  ratios: string[];
  resolutions?: string[];
  maxDuration?: number;
  referenceLimit: number;
  identity: number;
  quality: number;
  speed: number;
  costUsd: number;
  costUnit?: "image" | "second" | "request";
  enabledByDefault?: boolean;
  version?: string;
  config?: Record<string, unknown>;
}

export const PROVIDERS: Array<{ id: string; displayName: string }> = [
  { id: "kie", displayName: "kie.ai" },
  { id: "higgsfield", displayName: "Higgsfield" },
  { id: "fal", displayName: "fal.ai" },
  { id: "replicate", displayName: "Replicate" },
  { id: "runway", displayName: "Runway" },
  { id: "luma", displayName: "Luma" },
  { id: "topview", displayName: "Topview" },
  { id: "mock", displayName: "Mock (offline)" },
];

const IMG_RATIOS = ["1:1", "4:5", "3:4", "2:3", "9:16", "16:9", "4:3", "3:2"];

export const CATALOG: CatalogModel[] = [
  // ---------------------------------------------------------------- kie.ai
  {
    provider: "kie",
    model: "nano-banana-pro",
    displayName: "Nano Banana Pro (kie)",
    capabilities: ["text_to_image", "reference_image", "image_edit"],
    ratios: IMG_RATIOS,
    resolutions: ["2K", "1K", "4K"],
    referenceLimit: 8,
    identity: 0.85,
    quality: 0.9,
    speed: 0.6,
    costUsd: 0.12,
    config: { refField: "image_input", outputFormat: "jpg" },
  },
  {
    provider: "kie",
    model: "nano-banana-2",
    displayName: "Nano Banana 2 (kie)",
    capabilities: ["text_to_image", "reference_image", "image_edit"],
    ratios: IMG_RATIOS,
    resolutions: ["2K", "1K", "4K"],
    referenceLimit: 14,
    identity: 0.8,
    quality: 0.85,
    speed: 0.7,
    costUsd: 0.08,
    config: { refField: "image_input", outputFormat: "jpg", promptLimit: 20000 },
  },
  {
    provider: "kie",
    model: "google/nano-banana-edit",
    displayName: "Nano Banana Edit (kie)",
    capabilities: ["image_edit", "reference_image"],
    ratios: IMG_RATIOS,
    referenceLimit: 10,
    identity: 0.75,
    quality: 0.75,
    speed: 0.8,
    costUsd: 0.04,
    config: { refField: "image_urls", outputFormat: "jpeg", promptLimit: 5000 },
  },
  {
    provider: "kie",
    model: "gpt-image-2-5-flare-image-to-image",
    displayName: "GPT Image 2.5 Flare (kie)",
    capabilities: ["reference_image", "image_edit"],
    ratios: ["1:1", "3:4", "4:3", "2:3", "3:2"],
    resolutions: ["2K", "1K"],
    referenceLimit: 16,
    identity: 0.7,
    quality: 0.85,
    speed: 0.5,
    costUsd: 0.06,
    config: { refField: "input_urls" },
  },
  {
    provider: "kie",
    model: "bytedance/seedance-2-5",
    displayName: "Seedance 2.5 image→video (kie)",
    capabilities: ["image_to_video", "text_to_video", "audio"],
    ratios: ["9:16", "1:1", "3:4", "4:3", "16:9"],
    resolutions: ["720p", "480p", "1080p"],
    maxDuration: 30,
    referenceLimit: 4,
    identity: 0.75,
    quality: 0.85,
    speed: 0.4,
    costUsd: 0.06,
    costUnit: "second",
    config: { sourceField: "first_frame_url", refField: "reference_image_urls", durationFormat: "number", audioField: "generate_audio" },
  },
  {
    provider: "kie",
    model: "topaz/image-upscale",
    displayName: "Topaz upscale (kie)",
    capabilities: ["upscale"],
    ratios: [],
    referenceLimit: 0,
    identity: 1,
    quality: 0.9,
    speed: 0.6,
    costUsd: 0.05,
    config: { sourceField: "image_url", extra: { upscale_factor: "2" } },
  },
  // ---------------------------------------------------------------- Higgsfield
  {
    provider: "higgsfield",
    model: "higgsfield-ai/soul/v2/standard",
    displayName: "Soul 2 (Higgsfield, Soul ID)",
    capabilities: ["text_to_image", "soul"],
    ratios: ["9:16", "3:4", "1:1", "4:3", "16:9", "2:3", "3:2"],
    resolutions: ["1080p", "720p"],
    referenceLimit: 0,
    identity: 0.6,
    quality: 0.85,
    speed: 0.7,
    costUsd: 0.01,
    config: { soul: true, referenceStrength: 0.9, extra: { batch_size: 1, enhance_prompt: false } },
  },
  {
    provider: "higgsfield",
    model: "higgsfield-ai/soul/cinema",
    displayName: "Soul Cinema (Higgsfield, Soul ID)",
    capabilities: ["text_to_image", "soul"],
    ratios: ["9:16", "3:4", "1:1", "4:3", "16:9", "2:3", "3:2"],
    resolutions: ["1080p", "720p"],
    referenceLimit: 0,
    identity: 0.6,
    quality: 0.9,
    speed: 0.6,
    costUsd: 0.01,
    config: { soul: true, referenceStrength: 0.9, extra: { batch_size: 1 } },
  },
  {
    provider: "higgsfield",
    model: "kling-video/v3.0/std/image-to-video",
    displayName: "Kling 3.0 image→video (Higgsfield)",
    capabilities: ["image_to_video", "audio"],
    ratios: [],
    maxDuration: 15,
    referenceLimit: 1,
    identity: 0.75,
    quality: 0.85,
    speed: 0.4,
    costUsd: 0.112,
    costUnit: "second",
    config: { sourceField: "image_url", durationFormat: "number" },
  },
  // ---------------------------------------------------------------- fal.ai
  {
    provider: "fal",
    model: "fal-ai/nano-banana-pro/edit",
    displayName: "Nano Banana Pro edit (fal)",
    capabilities: ["reference_image", "image_edit"],
    ratios: ["4:5", "1:1", "3:4", "2:3", "9:16", "16:9", "4:3", "3:2", "5:4", "21:9"],
    resolutions: ["2K", "1K", "4K"],
    referenceLimit: 8,
    identity: 0.85,
    quality: 0.9,
    speed: 0.6,
    costUsd: 0.15,
    config: { refField: "image_urls", outputFormat: "jpeg", extra: { num_images: 1 } },
  },
  {
    provider: "fal",
    model: "fal-ai/nano-banana-pro",
    displayName: "Nano Banana Pro (fal)",
    capabilities: ["text_to_image"],
    ratios: ["4:5", "1:1", "3:4", "2:3", "9:16", "16:9", "4:3", "3:2", "5:4", "21:9"],
    resolutions: ["2K", "1K", "4K"],
    referenceLimit: 0,
    identity: 0.3,
    quality: 0.9,
    speed: 0.6,
    costUsd: 0.15,
    config: { outputFormat: "jpeg", extra: { num_images: 1 } },
  },
  {
    provider: "fal",
    model: "fal-ai/topaz/upscale/image",
    displayName: "Topaz upscale (fal)",
    capabilities: ["upscale"],
    ratios: [],
    referenceLimit: 0,
    identity: 1,
    quality: 0.9,
    speed: 0.6,
    costUsd: 0.08,
    config: { sourceField: "image_url", extra: { upscale_factor: 2, face_enhancement: true } },
  },
  {
    provider: "fal",
    model: "fal-ai/kling-video/v3/pro/image-to-video",
    displayName: "Kling 3 Pro image→video (fal)",
    capabilities: ["image_to_video", "audio"],
    ratios: [],
    maxDuration: 15,
    referenceLimit: 1,
    identity: 0.75,
    quality: 0.9,
    speed: 0.35,
    costUsd: 0.112,
    costUnit: "second",
    config: { sourceField: "start_image_url", durationFormat: "string", audioField: "generate_audio", negativeField: "negative_prompt" },
  },
  // ---------------------------------------------------------------- Replicate
  {
    provider: "replicate",
    model: "google/nano-banana-pro",
    displayName: "Nano Banana Pro (Replicate)",
    capabilities: ["text_to_image", "reference_image", "image_edit"],
    ratios: IMG_RATIOS,
    resolutions: ["2K", "1K", "4K"],
    referenceLimit: 14,
    identity: 0.85,
    quality: 0.9,
    speed: 0.55,
    costUsd: 0.15,
    config: { refField: "image_input", outputFormat: "jpg", extra: { allow_fallback_model: false } },
  },
  {
    provider: "replicate",
    model: "topazlabs/image-upscale",
    displayName: "Topaz upscale (Replicate)",
    capabilities: ["upscale"],
    ratios: [],
    referenceLimit: 0,
    identity: 1,
    quality: 0.9,
    speed: 0.6,
    costUsd: 0.05,
    config: { sourceField: "image", extra: { upscale_factor: "2x", face_enhancement: true } },
  },
  {
    provider: "replicate",
    model: "kwaivgi/kling-v3-video",
    displayName: "Kling 3 video (Replicate)",
    capabilities: ["image_to_video", "text_to_video", "audio"],
    ratios: ["9:16", "1:1", "16:9"],
    maxDuration: 10,
    referenceLimit: 1,
    identity: 0.75,
    quality: 0.85,
    speed: 0.35,
    costUsd: 0.12,
    costUnit: "second",
    config: { sourceField: "start_image", durationFormat: "number", audioField: "generate_audio", negativeField: "negative_prompt", extra: { mode: "standard" } },
  },
  // ---------------------------------------------------------------- Runway
  {
    provider: "runway",
    model: "gen4_image",
    displayName: "Gen-4 Image (Runway)",
    capabilities: ["text_to_image", "reference_image"],
    ratios: ["9:16", "16:9", "1:1", "4:3", "3:4"],
    referenceLimit: 3,
    identity: 0.8,
    quality: 0.85,
    speed: 0.6,
    costUsd: 0.08,
    config: { endpoint: "text_to_image", ratioMap: { "9:16": "1080:1920", "16:9": "1920:1080", "1:1": "1024:1024", "4:3": "1440:1080", "3:4": "1080:1440" } },
  },
  {
    provider: "runway",
    model: "gen4.5",
    displayName: "Gen-4.5 image→video (Runway)",
    capabilities: ["image_to_video"],
    ratios: ["9:16", "16:9", "1:1", "4:3", "3:4"],
    maxDuration: 10,
    referenceLimit: 1,
    identity: 0.75,
    quality: 0.9,
    speed: 0.35,
    costUsd: 0.12,
    costUnit: "second",
    config: { endpoint: "image_to_video", durations: [5, 10], ratioMap: { "9:16": "720:1280", "16:9": "1280:720", "1:1": "960:960", "4:3": "1104:832", "3:4": "832:1104" } },
  },
  // ---------------------------------------------------------------- Luma
  {
    provider: "luma",
    model: "uni-1",
    displayName: "Uni-1 (Luma)",
    capabilities: ["text_to_image", "reference_image"],
    ratios: ["1:1", "4:5", "3:4", "2:3", "9:16", "16:9", "4:3", "3:2"],
    referenceLimit: 9,
    identity: 0.75,
    quality: 0.8,
    speed: 0.7,
    costUsd: 0.045,
  },
  {
    provider: "luma",
    model: "uni-1-max",
    displayName: "Uni-1 Max (Luma)",
    capabilities: ["text_to_image", "reference_image"],
    ratios: ["1:1", "4:5", "3:4", "2:3", "9:16", "16:9", "4:3", "3:2"],
    referenceLimit: 9,
    identity: 0.8,
    quality: 0.88,
    speed: 0.55,
    costUsd: 0.105,
  },
  {
    provider: "luma",
    model: "ray-3.2",
    displayName: "Ray 3.2 video (Luma)",
    capabilities: ["image_to_video", "text_to_video"],
    ratios: ["9:16", "1:1", "16:9", "4:3", "3:4"],
    maxDuration: 10,
    referenceLimit: 1,
    identity: 0.7,
    quality: 0.85,
    speed: 0.4,
    costUsd: 0.06,
    costUnit: "second",
  },
  // ---------------------------------------------------------------- Topview
  {
    provider: "topview",
    model: "nano-banana-pro",
    displayName: "Nano Banana Pro (Topview)",
    capabilities: ["text_to_image", "reference_image", "image_edit"],
    ratios: ["1:1", "4:5", "3:4", "2:3", "9:16", "16:9", "4:3", "3:2"],
    resolutions: ["2K", "1K", "4K"],
    referenceLimit: 8,
    identity: 0.85,
    quality: 0.9,
    speed: 0.5,
    costUsd: 0.1,
    config: { topviewModel: "Nano Banana Pro" },
  },
  {
    provider: "topview",
    model: "kling-v3",
    displayName: "Kling V3 image→video (Topview)",
    capabilities: ["image_to_video", "text_to_video", "audio"],
    ratios: ["9:16", "1:1", "16:9"],
    maxDuration: 10,
    referenceLimit: 1,
    identity: 0.75,
    quality: 0.85,
    speed: 0.35,
    costUsd: 0.05,
    costUnit: "second",
    config: { topviewModel: "Kling V3" },
  },
  // ---------------------------------------------------------------- offline
  {
    provider: "mock",
    model: "mock-image",
    displayName: "Mock image (offline)",
    capabilities: ["text_to_image", "reference_image", "image_edit", "upscale"],
    ratios: [],
    referenceLimit: 16,
    identity: 0.3,
    quality: 0.2,
    speed: 1,
    costUsd: 0,
  },
  {
    provider: "mock",
    model: "mock-video",
    displayName: "Mock video (offline)",
    capabilities: ["image_to_video", "text_to_video"],
    ratios: [],
    maxDuration: 10,
    referenceLimit: 1,
    identity: 0.3,
    quality: 0.2,
    speed: 1,
    costUsd: 0,
    costUnit: "second",
  },
];
